# fly.toml app configuration file generated for llmo on 2024-12-02T16:46:33+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'llmo'
primary_region = 'mad'
console_command = '/rails/bin/rails console'

[env]
  HTTP_PORT = '8080'
  SOLID_QUEUE_IN_PUMA = 'true'

[processes]
  app = 'bundle exec thrust ./bin/rails server'
  solidq = 'bundle exec rake solid_queue:start'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[checks]
  [checks.status]
    port = 8080
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [checks.status.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 4
