default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  a_periodic_job:
    class: ProcessZombieReports
    schedule: every 10 seconds
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
